### PR TITLE
chore: Use the favicon from the stack

### PR DESCRIPTION
**Pull request by kosssi**
The favicon from the stack can be customized for B2B via the dynamic
assets, and it should be used for the core apps.

[Ref](https://github.com/cozy/cozy-banks/pull/920/commits/3098e9cb713551d327d1dbdac4b5aa2296dc80cd)

### CODE REVIEW

**Comment by CPatchane** [comment]
I think I miss some context here but I have to understand the purpose.
Why should "community" apps use the stack B2B favicon? Is it not supposed to be specific to our "platform" applications? Will this mean that all applications should stop provide the favicon? What happens if we have two favicons definitions?

**Comment by nono** [comment]
The current version of CCA doesn't provide any favicons. It would be nice if CCA provide by default a favicon and using the stack favicon can be a temporary workaround.

**Comment by nono** [comment]
Just saw #1069, I think we can close this PR

**Comment by CPatchane** [comment]
Ok then.

**Pull request closed without merging**
